DEBUG = True
LOGGING_CONFIG = "config/logging/local.conf"
PORT = 3000
APP_NAME = "throwstats"
# SQLALCHEMY_DATABASE_URI = 'sqlite:///../data/predictions.db'
# SQLALCHEMY_TRACK_MODIFICATIONS = True
HOST = "18.222.222.153"
# SQLALCHEMY_ECHO = False  # If true, SQL for queries made will be printed
# MAX_ROWS_SHOW = 100