train_model:
  data_address: "../data/throws_clean.csv"
  analysis_cols: ["GEO_Xstart","GEO_Ystart","Xdist","Ydist",""]
  train_share: 1
  response_col: "completion"
  random_state: 0
  CV_folds: 10
  model_address: "../models/trained_model.pkl"

app:
  model_address: "../models/trained_model.pkl"