train_model:
  data_address: "data/analysis_data.csv"
  analysis_cols: ["Xdist","Ydist","Stall"]
  response_col: ["completion"]
  random_state: 0
  CV_folds: 10
  model_address: "models/trained_model.pkl"

score_model:
  data_address: "data/throws_clean.csv"
  model_address: "models/trained_model.pkl"

generate_features:
  input_address: "data/throws_clean.csv"
  output_address: "data/analysis_data.csv"

app:
  model_address: "models/trained_model.pkl"

test:
  gen_features_data: "data/throws_clean.csv"