# Imports
import logging
import yaml 
import pickle
import pandas as pd

def generate_score(model, input):
    """ Generates a score for given input data from a logistic regression model
    Args:
        model (sklearn model object): A logistic regression model
        input (:py:class:`pandas.DataFrame`): DataFrame containing a users input data for which to generate a prediction
    Returns:
        score (float): The model generated by regressing the response over the features
    """
    score = model.predict_proba(input)
    score = score[0][1]

    return score

if __name__ == "__main__":
    # Load configuration
    with open("config/config.yml","r") as yml:
        config = yaml.load(yml)
    config = config["score_model"]

    # Load model from pickle file
    model = pickle.load( open( config["model_address"], "rb" ) )

    # If running file itself, load example data and output prediction
    user_input = pd.DataFrame(data={ "Xdist":[30.0], "Ydist":[-5.0], "Stall":[4]})
    print(generate_score(model, user_input))
